wandb_version: 1

BW_Maps:
  desc: null
  value: 2
BW_Req:
  desc: null
  value: 1.2
Baseline:
  desc: null
  value: Traffic Unaware
HighBW:
  desc: null
  value: 4
Map_Set:
  desc: null
  value: Traffic Test
Punish:
  desc: null
  value: 600
_wandb:
  desc: null
  value:
    cli_version: 0.12.1
    framework: tensorflow
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.13
    start_time: 1646775329
    t:
      1:
      - 3
      2:
      - 3
      3:
      - 2
      4: 3.6.13
      5: 0.12.1
      8:
      - 3
      - 5
timesteps:
  desc: null
  value: 300000
